"""Ticket schemas."""

from app.ticket.schemas.ticket import (
    TicketApproveRequest,
    TicketAssignRequest,
    TicketAssetInfo,
    TicketBase,
    TicketCategoryResponse,
    TicketCloseRequest,
    TicketCompleteRequest,
    TicketCreate,
    TicketDepartmentInfo,
    TicketFilterParams,
    TicketListResponse,
    TicketProgressUpdateRequest,
    TicketRejectRequest,
    TicketResponse,
    TicketStatsResponse,
    TicketUpdate,
    TicketUpdateRequest,
    TicketUserInfo,
    TicketWaitingInfoRequest,
)
from app.ticket.schemas.ticket_comment import (
    TicketCommentCreate,
    TicketCommentListResponse,
    TicketCommentResponse,
)

__all__ = [
    "TicketCategoryResponse",
    "TicketBase",
    "TicketCreate",
    "TicketUpdate",
    "TicketUpdateRequest",
    "TicketResponse",
    "TicketListResponse",
    "TicketApproveRequest",
    "TicketRejectRequest",
    "TicketAssignRequest",
    "TicketAssetInfo",
    "TicketCompleteRequest",
    "TicketProgressUpdateRequest",
    "TicketWaitingInfoRequest",
    "TicketCloseRequest",
    "TicketUserInfo",
    "TicketDepartmentInfo",
    "TicketFilterParams",
    "TicketStatsResponse",
    "TicketCommentCreate",
    "TicketCommentResponse",
    "TicketCommentListResponse",
]
