"""seed_ticket_categories

Revision ID: 007
Revises: 006
Create Date: 2026-03-10

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "007"
down_revision: Union[str, None] = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Default ticket categories (name, code). id generated by gen_random_uuid() in SQL.
DEFAULT_CATEGORIES = [
    ("Общий", "general"),
    ("ИТ и инфраструктура", "it"),
    ("Кадры и HR", "hr"),
    ("Бухгалтерия", "accounting"),
    ("Другое", "other"),
]


def upgrade() -> None:
    conn = op.get_bind()
    for name, code in DEFAULT_CATEGORIES:
        # Use distinct bind names so asyncpg does not deduce inconsistent types (text vs varchar)
        conn.execute(
            text("""
                INSERT INTO ticket_categories (id, name, code)
                SELECT gen_random_uuid(), :name, :code_val
                WHERE NOT EXISTS (SELECT 1 FROM ticket_categories WHERE code = :code_check)
            """),
            {"name": name, "code_val": code, "code_check": code},
        )


def downgrade() -> None:
    conn = op.get_bind()
    for _, code in DEFAULT_CATEGORIES:
        conn.execute(
            text("DELETE FROM ticket_categories WHERE code = :code"),
            {"code": code},
        )
