"""departments_add_number

Adds an admin-friendly auto-incrementing integer `number` column to
`departments`. The UUID `id` remains the primary key for all FKs; `number`
is a stable display alias surfaced in admin UI and Keycloak user attributes.

Strategy:
1. Add `number` as nullable INTEGER.
2. Backfill existing rows with sequential values ordered by `created_at`.
3. Mark NOT NULL and attach a UNIQUE constraint.
4. Convert to `GENERATED BY DEFAULT AS IDENTITY` so future inserts auto-fill.

Revision ID: 011
Revises: 010
Create Date: 2026-05-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "011"
down_revision: Union[str, None] = "010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "departments",
        sa.Column(
            "number",
            sa.Integer(),
            nullable=True,
            comment="Admin-friendly sequential department number",
        ),
    )

    op.execute(
        """
        WITH numbered AS (
            SELECT id,
                   ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn
            FROM departments
        )
        UPDATE departments d
        SET number = numbered.rn
        FROM numbered
        WHERE d.id = numbered.id
        """
    )

    op.alter_column("departments", "number", nullable=False)
    op.create_unique_constraint("uq_departments_number", "departments", ["number"])

    # Convert to identity. RESTART starts the sequence after the highest
    # backfilled value (or 1 when the table is empty).
    op.execute(
        """
        DO $$
        DECLARE
            next_val bigint;
        BEGIN
            SELECT COALESCE(MAX(number), 0) + 1 INTO next_val FROM departments;
            EXECUTE format(
                'ALTER TABLE departments '
                'ALTER COLUMN number ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH %s)',
                next_val
            );
        END$$;
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE departments ALTER COLUMN number DROP IDENTITY IF EXISTS"
    )
    op.drop_constraint("uq_departments_number", "departments", type_="unique")
    op.drop_column("departments", "number")
